version: '3'
services:
  web:
    build: .
    environment:
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}
      CALLBACK_URL: ${CALLBACK_URL}
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
